### ISSUE TITLE
[nav_goald_generator] Missing import for NavGoals service

### ISSUE THREAD

**Issue by cdondrup** [strands-project/strands_navigation#118]
```
Traceback (most recent call last):
  File "/opt/ros/hydro/lib/nav_goals_generator/nav_goals_generator.py", line 307, in <module>
    NavGoalsGenerator()
  File "/opt/ros/hydro/lib/nav_goals_generator/nav_goals_generator.py", line 85, in __init__
    self.ser = rospy.Service('/nav_goals', NavGoals, self.nav_goals_service)
NameError: global name 'NavGoals' is not defined
```

Must have happened when the service was moved inside the package. Will fix.

**Comment by cdondrup** [comment]
Closed via #119
