### ISSUE TITLE
Exception when helping with joystick

### ISSUE THREAD

**Issue by lucasb-eyer** [strands-project/strands_navigation#126]
When karl gets stuck, I help him with the (muxed) joystick because we don't have a GUI yet. It works and when I give up joystick control, he moves on, but I see the following:

```
[INFO] [WallTime: 1415963551.522795] Concurrent state 'NAV_SM' returned outcome 'succeeded' on termination.
[INFO] [WallTime: 1415963551.527681] Concurrent state 'pause_nav' returned outcome 'preempted' on termination.
[INFO] [WallTime: 1415963551.531063] Concurrent state 'stuck_on_carpet' returned outcome 'preempted' on termination.
[INFO] [WallTime: 1415963551.532216] Concurrent Outcomes: {'pause_nav': 'preempted', 'NAV_SM': 'succeeded', 'stuck_on_carpet': 'preempted', 'bumper': 'preempted'}
[INFO] [WallTime: 1415963551.532414] Concurrent state 'bumper' returned outcome 'preempted' on termination.
[INFO] [WallTime: 1415963551.532795] State machine terminating 'MONITORED_NAV':'succeeded':'succeeded'
[INFO] [WallTime: 1415963551.533156] SUCCEEDED
[ERROR] [WallTime: 1415963551.534700] InvalidUserCodeError: Could not execute child termination callback: Traceback (most recent call last):
  File "/opt/ros/hydro/lib/python2.7/dist-packages/smach/concurrence.py", line 348, in _state_runner
    preempt_others = self._child_termination_cb(self._child_outcomes)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/monitored_navigation/navigation.py", line 201, in child_term_cb
    if  outcome_map[name] == 'invalid':
KeyError: 'pause_nav'

Exception in thread concurrent_split:bumper:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 504, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/smach/concurrence.py", line 350, in _state_runner
    raise smach.InvalidUserCodeError("Could not execute child termination callback: "+traceback.format_exc())
InvalidUserCodeError: <smach.exceptions.InvalidUserCodeError instance at 0x7f953c17a4d0>

[INFO] [WallTime: 1415963552.291340] setting parameters back
[INFO] [WallTime: 1415963552.292545] navigation finished on Friday, November 14 2014, at 12:12:32 hours (24/2)
[INFO] [WallTime: 1415963552.292878] Waiting for services...
[INFO] [WallTime: 1415963552.300414] Done                                        
```

**Comment by bfalacerda** [comment]
will look into it

**Comment by lucasb-eyer** [comment]
Not urgent because it still "seems" to work, just thought I'd report it before I lose it.

**Comment by bfalacerda** [comment]
I also seen this once in a while but it didn't affect anything. Since after the changes in https://github.com/strands-project/strands_navigation/pull/134  I haven't seen it happening again. If someone sees it after it is merged please tell me something

**Comment by bfalacerda** [comment]
this is the smach concurrency bug that people have been complaining about. I'll close it for now and check if it disappears when we start using the indigo-devel branch of smach. if not i'll open a new issue to look at the smach concurrency
