### ISSUE TITLE
Error processing request: field goal.text must be of type str

### ISSUE THREAD

**Issue by lucasb-eyer** [strands-project/strands_navigation#137]
When the robot's bumper hit something, I saw this `ERROR` (with a bit of context):

```
[INFO] [WallTime: 1416324189.110502] State machine transitioning 'MONITORED_NAV':'bumper_fail'-->'bumper_recover
'
[INFO] [WallTime: 1416324189.111786] State machine starting in initial state 'RESTART_BUMPER' with userdata: 
        ['recovered']
[INFO] [WallTime: 1416324190.113456] State machine transitioning 'RESTART_BUMPER':'restarted'-->'BUMPER_HELP'
[INFO] [WallTime: 1416324230.314577] State machine transitioning 'BUMPER_HELP':'try_restart'-->'RESTART_BUMPER'
[INFO] [WallTime: 1416324231.316258] State machine transitioning 'RESTART_BUMPER':'restarted'-->'BUMPER_HELP'
[INFO] [WallTime: 1416324271.355499] State machine transitioning 'BUMPER_HELP':'try_restart'-->'RESTART_BUMPER'
[INFO] [WallTime: 1416324272.357357] State machine transitioning 'RESTART_BUMPER':'restarted'-->'BUMPER_HELP'
[INFO] [WallTime: 1416324290.286259] Preempt on state machine requested!
[ERROR] [WallTime: 1416324290.454105] Error processing request: field goal.text must be of type str
['Traceback (most recent call last):\n', '  File "/opt/ros/hydro/lib/python2.7/dist-packages/rospy/impl/tcpros_s
ervice.py", line 623, in _handle_request\n    response = convert_return_to_response(self.handler(request), self.response_class)\n', '  File "/opt/ros/hydro/lib/python2.7/dist-packages/monitored_navigation/help_manager.py", line 50, in forward_callback\n    helper.process_help_request(req)\n', '  File "/opt/ros/hydro/lib/python2.7/dist-packages/monitored_navigation/ui_helper.py", line 21, in process_help_request\n    self.help_failed(req.failed_component, req.interaction_service,req.n_fails)\n', '  File "/opt/ros/hydro/lib/python2.7/dist-packages/strands_human_help/help_speech.py", line 53, in help_failed\n    self.call_speech(self.help_failed)\n', '  File "/opt/ros/hydro/lib/python2.7/dist-packages/strands_human_help/help_speech.py", line 57, in call_speech\n    self.speaker.send_goal(maryttsGoal(text=text))\n', '  File "/opt/ros/hydro/lib/python2.7/dist-packages/actionlib/simple_action_client.py", line 92, in send_goal\n    self.gh = self.action_client.send_goal(goal, self._handle_transition, self._handle_feedback)\n', '  File "/opt/ros/hydro/lib/python2.7/dist-packages/actionlib/action_client.py", line 542, in send_goal\n    return self.manager.init_goal(goal, transition_cb, feedback_cb)\n', '  File "/opt/ros/hydro/lib/python2.7/dist-packages/actionlib/action_client.py", line 458, in init_goal\n    self.send_goal_fn(action_goal)\n', '  File "/opt/ros/hydro/lib/python2.7/dist-packages/rospy/topics.py", line 802, in publish\n    raise ROSSerializationException(str(e))\n', 'ROSSerializationException: field goal.text must be of type str\n']
[WARN] [WallTime: 1416324290.454684] No means of asking for human help available.
```

**Comment by lucasb-eyer** [comment]
Forgot to add that after that happened, I couldn't get him to move (using `rosrun topological_navigation nav_client.py NODE`) anymore and had to restart the navigation stack.

**Comment by marc-hanheide** [comment]
@BFALacerda? Looks like a version mix to me again... Are you sure you are not overlaying the global install with some outdated local checkout?

**Comment by bfalacerda** [comment]
no, its a small bug, correcting it now

**Comment by bfalacerda** [comment]
done, closing
