### ISSUE TITLE
Navigation state machine gets stuck

### ISSUE THREAD

**Issue by hawesie** [strands-project/strands_navigation#148]
When on the charging station, given a new goalnode off the station, the state machine hung like so: @BFALacerda 

```
[INFO] [WallTime: 1416587118.235077] Concurrent state 'bumper' returned outcome 'preempted' on termination.                                                              [51/1977]
[INFO] [WallTime: 1416587118.238656] Concurrent state 'stuck_on_carpet' returned outcome 'preempted' on termination.
[INFO] [WallTime: 1416587118.240053] Concurrent Outcomes: {'stuck_on_carpet': 'preempted', 'magnetic_strip': 'preempted', 'service_pause_nav': 'preempted', 'bumper': 'preempted',
 'pad_pause_nav': 'preempted', 'NAV_SM': 'succeeded'}
[INFO] [WallTime: 1416587118.240952] State machine terminating 'MONITORED_NAV':'succeeded':'succeeded'
[INFO] [WallTime: 1416587118.241649] SUCCEEDED
[INFO] [WallTime: 1416587118.592642] setting parameters back
[INFO] [WallTime: 1416587118.593079] navigation finished on Friday, November 21 2014, at 16:25:18 hours (48/9)
[INFO] [WallTime: 1416587118.593431] Waiting for services...
[INFO] [WallTime: 1416587118.601426] Done
[INFO] [WallTime: 1416587137.647372] /topological_navigation: Navigating From ChargingPoint to WayPoint16
[INFO] [WallTime: 1416587137.648016] 6 Nodes on route
Do move_base to ChargingPoint
[INFO] [WallTime: 1416587137.722315] State machine starting in initial state 'MONITORED_NAV' with userdata: 
        ['goal', 'result']
[INFO] [WallTime: 1416587137.722747] Concurrence starting with userdata: 
        ['goal']
[INFO] [WallTime: 1416587137.731941] State machine starting in initial state 'NAVIGATION' with userdata: 
        ['goal', 'n_nav_fails']
[ERROR] [1416587137.736321748]: Quaternion has length close to zero... discarding as navigation goal
[INFO] [WallTime: 1416587137.741386] State machine transitioning 'NAVIGATION':'planner_failure'-->'RECOVER_NAVIGATION'
[INFO] [WallTime: 1416587137.750265] State machine starting in initial state 'CLEAR_COSTMAPS' with userdata: 
        ['goal', 'n_nav_fails']
[ INFO] [1416587142.825377373]: Requesting the map...
[ INFO] [1416587143.140471395]: Received a 4000 X 4000 map at 0.050000 m/pix
[ INFO] [1416587143.168593684]: Requesting the map...
[ WARN] [1416587143.363818602]: Map update loop missed its desired rate of 5.0000Hz... the loop actually took 0.2048 seconds
[ INFO] [1416587143.600470677]: Received a 4000 X 4000 map at 0.050000 m/pix
[INFO] [WallTime: 1416587144.002322] Waiting for services...
[INFO] [WallTime: 1416587144.010832] Done
[INFO] [WallTime: 1416587144.042484] State machine terminating 'CLEAR_COSTMAPS':'try_nav':'recovered_without_help'
[INFO] [WallTime: 1416587144.043485] State machine terminating 'RECOVER_NAVIGATION':'recovered_without_help':'recovered_without_help'
[INFO] [WallTime: 1416587144.044158] Concurrent state 'NAV_SM' returned outcome 'recovered_without_help' on termination.
[INFO] [WallTime: 1416587144.048207] Concurrent state 'magnetic_strip' returned outcome 'preempted' on termination.
[INFO] [WallTime: 1416587144.055992] Concurrent state 'service_pause_nav' returned outcome 'preempted' on termination.
[INFO] [WallTime: 1416587144.059743] Concurrent state 'pad_pause_nav' returned outcome 'preempted' on termination.
[INFO] [WallTime: 1416587144.061339] Concurrent state 'bumper' returned outcome 'preempted' on termination.
[INFO] [WallTime: 1416587144.064483] Concurrent state 'stuck_on_carpet' returned outcome 'preempted' on termination.
[INFO] [WallTime: 1416587144.066205] Concurrent Outcomes: {'stuck_on_carpet': 'preempted', 'magnetic_strip': 'preempted', 'service_pause_nav': 'preempted', 'bumper': 'preempted',
 'pad_pause_nav': 'preempted', 'NAV_SM': 'recovered_without_help'}
[INFO] [WallTime: 1416587144.067269] State machine terminating 'MONITORED_NAV':'recovered_without_help':'recovered_without_help'
[INFO] [WallTime: 1416587144.068019] ABORTED
[ WARN] [1416587144.111240096]: Map update loop missed its desired rate of 5.0000Hz... the loop actually took 0.3523 seconds
[INFO] [WallTime: 1416587144.429280] 6 Nodes on route
Do move_base to ChargingPoint
[INFO] [WallTime: 1416587144.477085] State machine starting in initial state 'MONITORED_NAV' with userdata: 
        ['goal', 'result']
[INFO] [WallTime: 1416587144.477684] Concurrence starting with userdata: 
        ['goal']
[INFO] [WallTime: 1416587144.485272] State machine starting in initial state 'NAVIGATION' with userdata: 
        ['goal', 'n_nav_fails']
[ERROR] [1416587144.498562724]: Quaternion has length close to zero... discarding as navigation goal
[INFO] [WallTime: 1416587144.503284] State machine transitioning 'NAVIGATION':'planner_failure'-->'RECOVER_NAVIGATION'
[INFO] [WallTime: 1416587144.505060] State machine starting in initial state 'CLEAR_COSTMAPS' with userdata: 
        ['goal', 'n_nav_fails']
[ INFO] [1416587149.625316366]: Requesting the map...
[ INFO] [1416587149.945208857]: Received a 4000 X 4000 map at 0.050000 m/pix
[ INFO] [1416587149.972409603]: Requesting the map...
[ WARN] [1416587150.197383020]: Map update loop missed its desired rate of 5.0000Hz... the loop actually took 0.2384 seconds
[ INFO] [1416587150.273944860]: Received a 4000 X 4000 map at 0.050000 m/pix
[move_base-4] process has died [pid 7914, exit code -11, cmd /opt/ros/hydro/lib/move_base/move_base __name:=move_base __log:=/home/strands/.ros/log/e1233e40-7193-11e4-a881-00032d22587c/move_base-4.log].
log file: /home/strands/.ros/log/e1233e40-7193-11e4-a881-00032d22587c/move_base-4*.log
[ERROR] [WallTime: 1416587151.134984] InvalidUserCodeError: Could not execute state 'CLEAR_COSTMAPS' of type '<strands_monitored_nav_states.recover_nav_states.ClearCostmaps object at 0x24e0c10>': Traceback (most recent call last):
  File "/opt/ros/hydro/lib/python2.7/dist-packages/smach/state_machine.py", line 241, in _update_once
    self._remappings[self._current_label]))
  File "/opt/ros/hydro/lib/python2.7/dist-packages/strands_monitored_nav_states/recover_nav_states.py", line 49, in execute
    self.clear_costmaps()
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 435, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 525, in call
    raise ServiceException("transport error completing service call: %s"%(str(e)))
ServiceException: transport error completing service call: unable to receive data from sender, check sender's logs for details

[ERROR] [WallTime: 1416587151.135459] State 'RECOVER_NAVIGATION' failed to execute.
[ERROR] [WallTime: 1416587151.136015] InvalidStateError: Could not execute child state 'NAV_SM': Traceback (most recent call last):
  File "/opt/ros/hydro/lib/python2.7/dist-packages/smach/concurrence.py", line 326, in _state_runner
    self._remappings[label]))
  File "/opt/ros/hydro/lib/python2.7/dist-packages/smach/state_machine.py", line 347, in execute
    container_outcome = self._update_once()
  File "/opt/ros/hydro/lib/python2.7/dist-packages/smach/state_machine.py", line 244, in _update_once
    raise ex
InvalidUserCodeError: <smach.exceptions.InvalidUserCodeError instance at 0x7faac4048a70>

Exception in thread concurrent_split:NAV_SM:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 504, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/smach/concurrence.py", line 331, in _state_runner
    raise smach.InvalidStateError(("Could not execute child state '%s': " % label)+traceback.format_exc())
InvalidStateError: <smach.exceptions.InvalidStateError instance at 0x7faac4050560>

[INFO] [WallTime: 1416587151.143210] Concurrent state 'stuck_on_carpet' returned outcome 'preempted' on termination.
[INFO] [WallTime: 1416587151.144440] Concurrent state 'magnetic_strip' returned outcome 'preempted' on termination.
[INFO] [WallTime: 1416587151.149296] Concurrent state 'service_pause_nav' returned outcome 'preempted' on termination.
[INFO] [WallTime: 1416587151.150996] Concurrent state 'pad_pause_nav' returned outcome 'preempted' on termination.
[INFO] [WallTime: 1416587151.151991] Concurrent state 'bumper' returned outcome 'preempted' on termination.
```

**Comment by bfalacerda** [comment]
it's just catching an exception from the service call. It's weird the service call failing though, it's a service provided by move_base. I'm seeing too many map update failures, I think you should get it cropped

**Comment by hawesie** [comment]
Ok, I'll crop it.

If you're making concurrent calls with the same service proxy you might get issues. 

Why is it calling that function on undock though, as the cost maps are not involved.

**Comment by bfalacerda** [comment]
True, monitored_nav is unaware of that fact though... The perfect world would have different recoveries for different actions but there was no time to get that far
