### ISSUE TITLE
move_base died after door pass

### ISSUE THREAD

**Issue by hawesie** [strands-project/strands_navigation#155]
```
IN STATE PASS

GETTING FURTHER AWAY FROM GOAL

('leftMinim: %f, rightMinin:  %f \n', 0.385387889684557, 0.7524614556617635)
('base_cmd.linear.x = %f, base_cmd.angular.z= %f\n', 0.15, -0.734147131954413)
('leftMinim > 0.1 && rightMinim >0.1, updating: base_cmd.linear.x = %f, base_cmd.angular.z= %f\n', 0.2, 0)
('publishing to cmd_vel: base_cmd.linear.x = %f, base_cmd.angular.z= %f\n', 0.2, 0)
CHECKING PREEMPTED

IN STATE PASS

GETTING FURTHER AWAY FROM GOAL

('leftMinim: %f, rightMinin:  %f \n', 0.431747093383087, 0.7284459360947235)
('base_cmd.linear.x = %f, base_cmd.angular.z= %f\n', 0.15, -0.5933976854232731)
('leftMinim > 0.1 && rightMinim >0.1, updating: base_cmd.linear.x = %f, base_cmd.angular.z= %f\n', 0.2, 0)
getting further away from goal, going to state FAIL

('publishing to cmd_vel: base_cmd.linear.x = %f, base_cmd.angular.z= %f\n', 0.2, 0)
STOPPING

STOPPED

DOOR PASS FAILED

[INFO] [WallTime: 1416738587.911160] State machine transitioning 'NAVIGATION':'planner_failure'-->'RECOVER_NAVIGATION'
[INFO] [WallTime: 1416738587.911951] State machine starting in initial state 'CLEAR_COSTMAPS' with userdata: 
        ['goal', 'n_nav_fails']
[ INFO] [1416738593.093443994]: Requesting the map...
[ INFO] [1416738593.400545269]: Received a 4000 X 4000 map at 0.050000 m/pix
[ INFO] [1416738593.419713628]: Requesting the map...
[ INFO] [1416738593.854712333]: Received a 4000 X 4000 map at 0.050000 m/pix
[ WARN] [1416738593.887566309]: Map update loop missed its desired rate of 5.0000Hz... the loop actually took 0.3482 seconds
[WARN] [WallTime: 1416738594.107786] Issue clearing costmaps.
[INFO] [WallTime: 1416738594.108352] State machine transitioning 'CLEAR_COSTMAPS':'do_other_recovery'-->'BACKTRACK'
[move_base-7] process has died [pid 2247, exit code -11, cmd /opt/ros/hydro/lib/move_base/move_base /move_base/local_costmap/voxel_grid:=/voxel_grid __name:=move_base __log:=/home/strands/.ros/log/4d069c4
e-71a1-11e4-9515-00032d22587c/move_base-7.log].
log file: /home/strands/.ros/log/4d069c4e-71a1-11e4-9515-00032d22587c/move_base-7*.log
Got the previous position:  -3.51143007073 ,  -1.97553955057 ,  6.93889390391e-18
Managed to republish pointcloud.
[ERROR] [WallTime: 1416738598.358417] Exception in your execute callback: unable to connect to service: [Errno 111] Connection refused
Traceback (most recent call last):
  File "/opt/ros/hydro/lib/python2.7/dist-packages/actionlib/simple_action_server.py", line 299, in executeLoop
    self.execute_callback(goal)
  File "/opt/ros/hydro/lib/backtrack_behaviour/backtrack_server.py", line 163, in execute
    config = self.move_base_reconfig_client.update_configuration(params)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/client.py", line 212, in update_configuration
    msg    = self._set_service(config).config
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 435, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 505, in call
    raise ServiceException("unable to connect to service: %s"%e)
ServiceException: unable to connect to service: [Errno 111] Connection refused
```

**Comment by bfalacerda** [comment]
the calls to dynamic reconfig in the backtrack behaviours need to be wrapped on a try/catch statement. I can do it but I'm not 100% sure when the reset_ptu method needs to be called before termination. If @nilsbore can do it it would be safer

**Comment by hawesie** [comment]
The question is why did move_base die before that though?

**Comment by bfalacerda** [comment]
i dont see it dying before. Why do you think it died?

**Comment by bfalacerda** [comment]
ah ok

**Comment by bfalacerda** [comment]
I see it now

**Comment by bfalacerda** [comment]
`[WARN] [WallTime: 1416738594.107786] Issue clearing costmaps.`

There was an exception caught when calling the clear costmaps service before move_base died. It might not be culprit, but I'll remove the CLEAR_COSTMAPS state as it seems it's creating some random issues. This might not solve anything though

**Comment by nilsbore** [comment]
I'm gonna be at the office in an hour, can add the try catches then.
Den 23 nov 2014 12:14 skrev "BFALacerda" notifications@github.com:
