### ISSUE TITLE
AttributeError: 'TopologicalNavServer' object has no attribute 'stat'

### ISSUE THREAD

**Issue by hawesie** [strands-project/strands_navigation#161]
```
[ INFO] [1416825893.912783959]: Got new plan                                                                                                                                       │························
[ INFO] [1416825894.409034706]: Got new plan                                                                                                                                       │························
[INFO] [WallTime: 1416825894.601518] new node reached WayPoint10                                                                                                                   │························
[INFO] [WallTime: 1416825894.602231] new node reached WayPoint10                                                                                                                   │························
[ERROR] [WallTime: 1416825894.602922] bad callback: <bound method TopologicalNavServer.currentNodeCallback of <__main__.TopologicalNavServer object at 0x2530410>>                 │························
Traceback (most recent call last):                                                                                                                                                 │························
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rospy/topics.py", line 682, in _invoke_callback                                                                                 │························
    cb(msg)                                                                                                                                                                        │························
  File "/opt/ros/hydro/lib/topological_navigation/navigation.py", line 199, in currentNodeCallback                                                                                 │························
    self.stat.set_at_node()                                                                                                                                                        │························AttributeError: 'TopologicalNavServer' object has no attribute 'stat'                                                                                                              │························
                                                                                                                                                                                   │························
[ INFO] [1416825894.909078515]: Got new plan                                                                                                                                       │························
[ INFO] [1416825895.409004786]: Got new plan     
```

**Comment by Jailander** [comment]
@hawesie yes as I said in #159 this was introduced on Thursday (it was Friday) when we introduced the special cases it wasn't properly tested on Linda, this error however shouldn't crash the node does it?
Can the fix wait? I am with Linda at the museum can't test here

**Comment by hawesie** [comment]
No I don't think it crashed the node.

**Comment by Jailander** [comment]
So it can wait?

**Comment by hawesie** [comment]
Yeah.

**Comment by Jailander** [comment]
I will close as I have never seen this again, must have been fix by other PRs reopen if seen
