### ISSUE TITLE
problem with nav help service

### ISSUE THREAD

**Issue by bfalacerda** [strands-project/strands_navigation#334]
```[ERROR] [WallTime: 1479727557.571022] [Client 0] [id: call_service:/monitored_navigation/none:74] call_service InvalidServiceException: Service /monitored_navigation/none does not exist```

**Comment by bfalacerda** [comment]
this happened again, with bumper recovery - not sure which recovery was on when it happened last time. might the errors in this log be causing this? I do have a 'none' service string name but when that is sent the robto should display the main page... @hawesie any idea?

```

[INFO] [WallTime: 1480173168.472385] say Hi Nils. Do you have something you want delivered to Ferdi? Please put it in my basket, and press the button o
n my screen.
Request for:  /bootstrap/dist/css/bootstrap.min.css
10.0.11.161 - - [26/Nov/2016 15:12:48] "GET /bootstrap/dist/css/bootstrap.min.css HTTP/1.1" 200 -
doing bootstrap css
----------------------------------------
Exception happened during processing of request from ('10.0.11.161', 51276)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 651, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 710, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
----------------------------------------
Request for:  /roslibjs/include/EventEmitter2/eventemitter2.js
doing JAVASCRIPT
10.0.11.161 - - [26/Nov/2016 15:12:48] "GET /roslibjs/include/EventEmitter2/eventemitter2.js HTTP/1.1" 200 -
/opt/ros/indigo/share/strands_webtools/roslibjs/include/EventEmitter2/eventemitter2.js not available in strands_webtools
10.0.11.161 - - [26/Nov/2016 15:12:48] code 404, message File not found
10.0.11.161 - - [26/Nov/2016 15:12:48] "GET /roslibjs/include/EventEmitter2/eventemitter2.js HTTP/1.1" 404 -
----------------------------------------
Exception happened during processing of request from ('10.0.11.161', 51277)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock                                                            [300/3423]
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 651, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 710, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
----------------------------------------
Request for:  /roslibjs/build/roslib.js
doing JAVASCRIPT
10.0.11.161 - - [26/Nov/2016 15:12:48] "GET /roslibjs/build/roslib.js HTTP/1.1" 200 -
/opt/ros/indigo/share/strands_webtools/roslibjs/build/roslib.js not available in strands_webtools
10.0.11.161 - - [26/Nov/2016 15:12:48] code 404, message File not found
10.0.11.161 - - [26/Nov/2016 15:12:48] "GET /roslibjs/build/roslib.js HTTP/1.1" 404 -
----------------------------------------
Exception happened during processing of request from ('10.0.11.161', 51278)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 651, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 710, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
----------------------------------------
[INFO] [WallTime: 1480173168.959325] start playing sound
[INFO] [WallTime: 1480173168.960080] updated priority map: {'/ros_mary_bridge': 1.0}
[INFO] [WallTime: 1480173168.960319] setting volume to 1.000000
[INFO] [WallTime: 1480173176.765129] played
[INFO] [WallTime: 1480173168.960319] setting volume to 1.000000                                                                              [257/3423]
[INFO] [WallTime: 1480173176.765129] played
[INFO] [WallTime: 1480173176.765735] updated priority map: {'/ros_mary_bridge': 0.0}
[INFO] [WallTime: 1480173176.766482] setting volume to 1.000000
[INFO] [WallTime: 1480173228.493193] [(2, <rospy.topics.Publisher object at 0x7f95e66a7950>), (3, <rospy.topics.Publisher object at 0x7f95e41bcd10>)]
[INFO] [WallTime: 1480173228.503805] action triggered: say Sorry, but I can't wait for the package anymore, I have other things to do. See you later.
[INFO] [WallTime: 1480173228.504584] finished speaking...
[INFO] [WallTime: 1480173228.538657] say Sorry, but I can't wait for the package anymore, I have other things to do. See you later.
Request for:  /bootstrap/dist/css/bootstrap.min.css
10.0.11.161 - - [26/Nov/2016 15:13:48] "GET /bootstrap/dist/css/bootstrap.min.css HTTP/1.1" 200 -
doing bootstrap css
Request for:  /roslibjs/include/EventEmitter2/eventemitter2.js
doing JAVASCRIPT
10.0.11.161 - - [26/Nov/2016 15:13:48] "GET /roslibjs/include/EventEmitter2/eventemitter2.js HTTP/1.1" 200 -
Request for:  /roslibjs/build/roslib.js
doing JAVASCRIPT
10.0.11.161 - - [26/Nov/2016 15:13:48] "GET /roslibjs/build/roslib.js HTTP/1.1" 200 -
[INFO] [WallTime: 1480173228.802637] Client connected.  3 clients total.
Request for:  /bootstrap/dist/css/bootstrap.min.css
10.0.11.161 - - [26/Nov/2016 15:13:48] "GET /bootstrap/dist/css/bootstrap.min.css HTTP/1.1" 200 -
doing bootstrap css
[INFO] [WallTime: 1480173229.448997] start playing sound
[INFO] [WallTime: 1480173229.451068] updated priority map: {'/ros_mary_bridge': 1.0}
[INFO] [WallTime: 1480173229.451370] setting volume to 1.000000
[INFO] [WallTime: 1480173235.576988] updated priority map: {'/ros_mary_bridge': 0.0}
[INFO] [WallTime: 1480173235.577166] played
[INFO] [WallTime: 1480173235.577899] setting volume to 1.000000
[INFO] [WallTime: 1480173246.128222] [(2, <rospy.topics.Publisher object at 0x7f95e66a7950>), (3, <rospy.topics.Publisher object at 0x7f95e41bcd10>)]
[INFO] [WallTime: 1480173246.145372] Client disconnected. 2 clients total.
[INFO] [WallTime: 1480173246.270113] action triggered: say 
[WARN] [WallTime: 1480173246.270613] mary_tts was asked to produce an empty string.
[INFO] [WallTime: 1480173250.716135] [(2, <rospy.topics.Publisher object at 0x7f95e66a7950>), (3, <rospy.topics.Publisher object at 0x7f95e41bcd10>)]
Request for:  /bootstrap/dist/css/bootstrap.min.css
10.0.11.161 - - [26/Nov/2016 15:14:10] "GET /bootstrap/dist/css/bootstrap.min.css HTTP/1.1" 200 -
doing bootstrap css
Request for:  /roslibjs/include/EventEmitter2/eventemitter2.js
doing JAVASCRIPT
10.0.11.161 - - [26/Nov/2016 15:14:10] "GET /roslibjs/include/EventEmitter2/eventemitter2.js HTTP/1.1" 200 -
Request for:  /roslibjs/build/roslib.js
doing JAVASCRIPT
10.0.11.161 - - [26/Nov/2016 15:14:10] "GET /roslibjs/build/roslib.js HTTP/1.1" 200 -
[INFO] [WallTime: 1480173250.938308] Client connected.  3 clients total.
Request for:  /bootstrap/dist/css/bootstrap.min.css
10.0.11.161 - - [26/Nov/2016 15:14:10] "GET /bootstrap/dist/css/bootstrap.min.css HTTP/1.1" 200 -
doing bootstrap css
10.0.11.161 - - [26/Nov/2016 15:14:10] "GET /bootstrap/dist/css/bootstrap.min.css HTTP/1.1" 200 -                                            [214/3423]
doing bootstrap css
[INFO] [WallTime: 1480173251.021018] [(2, <rospy.topics.Publisher object at 0x7f95e66a7950>), (3, <rospy.topics.Publisher object at 0x7f95e41bcd10>)]
[INFO] [WallTime: 1480173251.073250] Client disconnected. 2 clients total.
[INFO] [WallTime: 1480173251.243183] [(2, <rospy.topics.Publisher object at 0x7f95e66a7950>), (3, <rospy.topics.Publisher object at 0x7f95e41bcd10>)]
Request for:  /bootstrap/dist/css/bootstrap.min.css
10.0.11.161 - - [26/Nov/2016 15:14:11] "GET /bootstrap/dist/css/bootstrap.min.css HTTP/1.1" 200 -
doing bootstrap css
[INFO] [WallTime: 1480173251.281486] action triggered: say 
[WARN] [WallTime: 1480173251.281850] mary_tts was asked to produce an empty string.
Request for:  /roslibjs/include/EventEmitter2/eventemitter2.js
doing JAVASCRIPT
10.0.11.161 - - [26/Nov/2016 15:14:11] "GET /roslibjs/include/EventEmitter2/eventemitter2.js HTTP/1.1" 200 -
Request for:  /roslibjs/build/roslib.js
doing JAVASCRIPT
10.0.11.161 - - [26/Nov/2016 15:14:11] "GET /roslibjs/build/roslib.js HTTP/1.1" 200 -
[INFO] [WallTime: 1480173251.427419] Client connected.  3 clients total.
Request for:  /bootstrap/dist/css/bootstrap.min.css
10.0.11.161 - - [26/Nov/2016 15:14:11] "GET /bootstrap/dist/css/bootstrap.min.css HTTP/1.1" 200 -
doing bootstrap css
[ERROR] [WallTime: 1480174459.248254] [Client 90] [id: call_service:/go_to_safety_point:1] call_service InvalidServiceException: Service /go_to_safety_
point does not exist
[ERROR] [WallTime: 1480174459.493101] [Client 90] [id: call_service:/go_to_safety_point:2] call_service InvalidServiceException: Service /go_to_safety_
point does not exist
[INFO] [WallTime: 1480175113.113091] action triggered: say I am stuck here, so I might try moving backwards. Please get out of the way.
[INFO] [WallTime: 1480175113.113576] finished speaking...
[INFO] [WallTime: 1480175113.129425] say I am stuck here, so I might try moving backwards. Please get out of the way.
[INFO] [WallTime: 1480175113.434647] start playing sound
[INFO] [WallTime: 1480175113.435286] updated priority map: {'/ros_mary_bridge': 1.0}
[INFO] [WallTime: 1480175113.435531] setting volume to 1.000000
[INFO] [WallTime: 1480175118.545099] updated priority map: {'/ros_mary_bridge': 0.0}
[INFO] [WallTime: 1480175118.545409] played
[INFO] [WallTime: 1480175118.545577] setting volume to 1.000000
[INFO] [WallTime: 1480175192.159816] action triggered: say I am stuck here, so I might try moving backwards. Please get out of the way.
[INFO] [WallTime: 1480175192.161951] finished speaking...
[INFO] [WallTime: 1480175192.173489] say I am stuck here, so I might try moving backwards. Please get out of the way.
[INFO] [WallTime: 1480175192.496691] start playing sound
[INFO] [WallTime: 1480175192.497205] updated priority map: {'/ros_mary_bridge': 1.0}
[INFO] [WallTime: 1480175192.497405] setting volume to 1.000000
[INFO] [WallTime: 1480175197.780804] played
[INFO] [WallTime: 1480175197.781300] updated priority map: {'/ros_mary_bridge': 0.0}
[INFO] [WallTime: 1480175197.781902] setting volume to 1.000000
[INFO] [WallTime: 1480175236.546201] action triggered: say I am stuck here, so I might try moving backwards. Please get out of the way.
[INFO] [WallTime: 1480175236.546645] finished speaking...
[INFO] [WallTime: 1480175236.553306] say I am stuck here, so I might try moving backwards. Please get out of the way.
[INFO] [WallTime: 1480175236.546645] finished speaking...                                                                                    [171/3423]
[INFO] [WallTime: 1480175236.553306] say I am stuck here, so I might try moving backwards. Please get out of the way.
[INFO] [WallTime: 1480175237.320683] start playing sound
[INFO] [WallTime: 1480175237.321318] updated priority map: {'/ros_mary_bridge': 1.0}
[INFO] [WallTime: 1480175237.321581] setting volume to 1.000000
[INFO] [WallTime: 1480175242.654813] played
[INFO] [WallTime: 1480175242.656665] updated priority map: {'/ros_mary_bridge': 0.0}
[INFO] [WallTime: 1480175242.657076] setting volume to 1.000000
[ERROR] [WallTime: 1480176085.823701] [Client 90] [id: call_service:/go_to_safety_point:3] call_service InvalidServiceException: Service /go_to_safety_
point does not exist
[ERROR] [WallTime: 1480176086.267420] [Client 90] [id: call_service:/go_to_safety_point:4] call_service InvalidServiceException: Service /go_to_safety_
point does not exist
[ERROR] [WallTime: 1480176086.485538] [Client 90] [id: call_service:/go_to_safety_point:5] call_service InvalidServiceException: Service /go_to_safety_
point does not exist
[ERROR] [WallTime: 1480176086.712405] [Client 90] [id: call_service:/go_to_safety_point:6] call_service InvalidServiceException: Service /go_to_safety_
point does not exist
[ERROR] [WallTime: 1480176086.899320] [Client 90] [id: call_service:/go_to_safety_point:7] call_service InvalidServiceException: Service /go_to_safety_
point does not exist
[ERROR] [WallTime: 1480176218.649756] [Client 90] [id: call_service:/go_to_safety_point:8] call_service InvalidServiceException: Service /go_to_safety_
point does not exist
[ERROR] [WallTime: 1480176218.895375] [Client 90] [id: call_service:/go_to_safety_point:9] call_service InvalidServiceException: Service /go_to_safety_
point does not exist
[ERROR] [WallTime: 1480176219.139047] [Client 90] [id: call_service:/go_to_safety_point:10] call_service InvalidServiceException: Service /go_to_safety
_point does not exist
[ERROR] [WallTime: 1480176219.376011] [Client 90] [id: call_service:/go_to_safety_point:11] call_service InvalidServiceException: Service /go_to_safety
_point does not exist
[ERROR] [WallTime: 1480176219.598441] [Client 90] [id: call_service:/go_to_safety_point:12] call_service InvalidServiceException: Service /go_to_safety
_point does not exist
[ERROR] [WallTime: 1480176220.026340] [Client 90] [id: call_service:/go_to_safety_point:13] call_service InvalidServiceException: Service /go_to_safety
_point does not exist
[ERROR] [WallTime: 1480176221.758615] [Client 90] [id: call_service:/go_to_safety_point:14] call_service InvalidServiceException: Service /go_to_safety
_point does not exist
[ERROR] [WallTime: 1480176223.681828] [Client 90] [id: call_service:/go_to_safety_point:15] call_service InvalidServiceException: Service /go_to_safety
_point does not exist
[ERROR] [WallTime: 1480176224.703126] [Client 90] [id: call_service:/go_to_safety_point:16] call_service InvalidServiceException: Service /go_to_safety
_point does not exist
[ERROR] [WallTime: 1480176227.387096] [Client 90] [id: call_service:/go_to_safety_point:17] call_service InvalidServiceException: Service /go_to_safety
_point does not exist
[ERROR] [WallTime: 1480176227.715362] [Client 90] [id: call_service:/go_to_safety_point:18] call_service InvalidServiceException: Service /go_to_safety
_point does not exist
[ERROR] [WallTime: 1480176230.537776] [Client 90] [id: call_service:/go_to_safety_point:19] call_service InvalidServiceException: Service /go_to_safety
_point does not exist
[ERROR] [WallTime: 1480176230.781919] [Client 90] [id: call_service:/go_to_safety_point:20] call_service InvalidServiceException: Service /go_to_safety
_point does not exist
[ERROR] [WallTime: 1480176249.781556] [Client 90] [id: call_service:/go_to_safety_point:21] call_service InvalidServiceException: Service /go_to_safety
_point does not exist                                                                                                                        [128/3423]
[ERROR] [WallTime: 1480176249.781556] [Client 90] [id: call_service:/go_to_safety_point:21] call_service InvalidServiceException: Service /go_to_safety
_point does not exist
[ERROR] [WallTime: 1480176250.016693] [Client 90] [id: call_service:/go_to_safety_point:22] call_service InvalidServiceException: Service /go_to_safety
_point does not exist
[ERROR] [WallTime: 1480176250.254110] [Client 90] [id: call_service:/go_to_safety_point:23] call_service InvalidServiceException: Service /go_to_safety
_point does not exist
[ERROR] [WallTime: 1480176250.517297] [Client 90] [id: call_service:/go_to_safety_point:24] call_service InvalidServiceException: Service /go_to_safety
_point does not exist
[ERROR] [WallTime: 1480176250.888848] [Client 90] [id: call_service:/go_to_safety_point:25] call_service InvalidServiceException: Service /go_to_safety
_point does not exist
[ERROR] [WallTime: 1480176254.053924] [Client 90] [id: call_service:/go_to_safety_point:26] call_service InvalidServiceException: Service /go_to_safety
_point does not exist
[ERROR] [WallTime: 1480176254.288069] [Client 90] [id: call_service:/go_to_safety_point:27] call_service InvalidServiceException: Service /go_to_safety
_point does not exist
[INFO] [WallTime: 1480176429.378723] [(2, <rospy.topics.Publisher object at 0x7f95e66a7950>), (3, <rospy.topics.Publisher object at 0x7f95e41bcd10>)]
[INFO] [WallTime: 1480176429.390443] Client disconnected. 2 clients total.
[ERROR] [WallTime: 1480176857.952888] [Client 36] [id: call_service:/monitored_navigation/none:15] call_service InvalidServiceException: Service /monit
ored_navigation/none does not exist
[ERROR] [WallTime: 1480176860.382603] [Client 36] [id: call_service:/monitored_navigation/none:16] call_service InvalidServiceException: Service /monit
ored_navigation/none does not exist
[ERROR] [WallTime: 1480176860.898343] [Client 36] [id: call_service:/monitored_navigation/none:17] call_service InvalidServiceException: Service /monit
ored_navigation/none does not exist
[ERROR] [WallTime: 1480176861.070713] [Client 36] [id: call_service:/monitored_navigation/none:18] call_service InvalidServiceException: Service /monit
ored_navigation/none does not exist
[ERROR] [WallTime: 1480176861.254467] [Client 36] [id: call_service:/monitored_navigation/none:19] call_service InvalidServiceException: Service /monit
ored_navigation/none does not exist
[ERROR] [WallTime: 1480176861.403096] [Client 36] [id: call_service:/monitored_navigation/none:20] call_service InvalidServiceException: Service /monit
ored_navigation/none does not exist
[ERROR] [WallTime: 1480176861.541900] [Client 36] [id: call_service:/monitored_navigation/none:21] call_service InvalidServiceException: Service /monit
ored_navigation/none does not exist
[ERROR] [WallTime: 1480176861.712478] [Client 36] [id: call_service:/monitored_navigation/none:22] call_service InvalidServiceException: Service /monit
ored_navigation/none does not exist
[ERROR] [WallTime: 1480176861.851964] [Client 36] [id: call_service:/monitored_navigation/none:23] call_service InvalidServiceException: Service /monit
ored_navigation/none does not exist
[ERROR] [WallTime: 1480176862.006099] [Client 36] [id: call_service:/monitored_navigation/none:24] call_service InvalidServiceException: Service /monit
ored_navigation/none does not exist
[ERROR] [WallTime: 1480176862.254589] [Client 36] [id: call_service:/monitored_navigation/none:25] call_service InvalidServiceException: Service /monit
ored_navigation/none does not exist
[ERROR] [WallTime: 1480176862.817739] [Client 36] [id: call_service:/monitored_navigation/none:26] call_service InvalidServiceException: Service /monit
ored_navigation/none does not exist
[ERROR] [WallTime: 1480176863.562928] [Client 36] [id: call_service:/monitored_navigation/none:27] call_service InvalidServiceException: Service /monit
ored_navigation/none does not exist
[ERROR] [WallTime: 1480176863.737189] [Client 36] [id: call_service:/monitored_navigation/none:28] call_service InvalidServiceException: Service /monit
ored_navigation/none does not exist

```

**Comment by bfalacerda** [comment]
there's also those errors with mary and the empty string, which come from the robot talk proxy or whatever that was called
